[package]
name = "workspace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
imap = "2.4.1"
ldap3 = "0.10.4"
native-tls = "0.2.10"
lettre = "0.9.0"
lettre_email = "0.9"
gtk = "0.15.5"